name: Release
on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
      - '[0-9]+.[0-9]+.[0-9]+-*'
env:
  DOTNET_NOLOGO: true
jobs:
  release:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.2
        with:
          fetch-depth: 0    
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v2.1.0
        with:
          dotnet-version: 3.1.x
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1.0
      - name: Build
        run: msbuild src -p:Configuration=Release -restore -m -p:RestorePackagesConfig=true
      - name: Install NuGetKeyVaultSignTool
        run: dotnet tool install --global NuGetKeyVaultSignTool
      - name: Sign NuGet Packages
        run: |
          NuGetKeyVaultSignTool sign nugets\*.nupkg `
          --file-digest sha256 `
          --timestamp-rfc3161 http://timestamp.digicert.com `
          --timestamp-digest sha256 `
          --azure-key-vault-url https://particularcodesigning.vault.azure.net `
          --azure-key-vault-client-id ${{ secrets.AZURE_KEY_VAULT_CLIENT_ID }} `
          --azure-key-vault-tenant-id ${{ secrets.AZURE_KEY_VAULT_TENANT_ID }} `
          --azure-key-vault-client-secret ${{ secrets.AZURE_KEY_VAULT_CLIENT_SECRET }} `
          --azure-key-vault-certificate ${{ secrets.AZURE_KEY_VAULT_CERTIFICATE_NAME }}
        shell: pwsh
      - name: Publish artifacts
        uses: actions/upload-artifact@v3.1.0
        with:
          name: nugets
          path: nugets/*
          retention-days: 1
      - name: Deploy
        uses: Particular/push-octopus-package-action@v1.0.0
        with:
          octopus-deploy-api-key: ${{ secrets.OCTOPUS_DEPLOY_API_KEY }}    